settings:
  title: 'SonekNet Status'
  url: 'https://status.soneknet.com' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: plex # unique identifier
    name: Plex
    description: 'Plex' # default=empty
    url: 'https://plex.soneknet.com/identity' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: request
    name: Requests
    description: ''
    url: 'https://request.soneknet.com'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: read
    name: Paywall Bypass
    url: 'https://read.soneknet.com/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: project
    name: Project Management
    url: 'https://www.project.soneknet.com/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
