settings:
  title: 'Status Page'
  url: 'https://status.dearborn.io' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: dearbornio # unique identifier
    name: DearbornIO
    description: 'DearbornIO Homepage' # default=empty
    url: 'https://dearborn.io/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: acreautoparts
    name: Acre Auto Parts
    description: ''
    url: 'https://www.acreautoparts.com'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: ac4jc
    name: American Cash For Junk Cars
    url: 'https://americancashforjunkcars.com/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

 - id: fairlanegardens
    name: Fairlane Gardens
    url: 'https://flgardens.com/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: hamoudydev
    name: Hamoudy.dev
    url: 'https://hamoudy.dev/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
